name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Stylelint and Configurations
        run: |
          npm install stylelint stylelint-config-standard

      - name: Run Stylelint
        run: |
          npx stylelint "**/*.css" --fix --ignore-pattern '**/*.min.css'          